settings:
  title: 'Sistem Bilgilendirme Sayfası'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Tüm Sistemler Stabil'
  notAllmonitorsOperational: 'Görünüşe Göre Bazı Sistemlerde Sorun Mevcut.'
  monitorLabelOperational: 'Stabil'
  monitorLabelNotOperational: 'Stabil Değil'
  monitorLabelNoData: 'Veri Yok'
  dayInHistogramNoData: 'Veri Yok'
  dayInHistogramOperational: 'Her şey Mükemmel.'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: map # unique identifier
    name: map.ytudogdok.me
    description: 'Server Map.' # default=empty
    url: 'https://map.ytudogdok.me/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: discord
    name: Discord Redirection
    description: 'YTU Discord'
    url: 'https://discord.ytudogdok.me'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

